name: pyscrapenv

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - pip:
      - requests2
      - pandas
      - lxml
      - beautifulsoup4
      - selenium
      - undetected-chromedriver
      - fake-useragent